
# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: xterm-256color
  TERM_PROGRAM: Alacritty.app
window:
  dimensions:
    columns: 80
    lines: 40
  dynamic_padding: false
  decorations: buttonless
  opacity: 0.9
  startup_mode: Windowed
  title: 'mikeTerm 666'
  # dynamic_title: true
scrolling:
  history: 10000
  multiplier: 3
font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  italic:
    family: Menlo
    style: Italic
  bold_italic:
    family: Menlo
    style: Bold Italic
  size: 16.0
  apple_font_smoothing: true
  builtin_box_drawing: false
draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: '#000000'
    foreground: '#c7c7c7'
    dim_foreground: '#828482'
    bright_foreground: '#feffff'
    transparent_background_colors: false
live_config_reload: true
shell:
  program: /Users/mbattiston/.tea/gnu.org/bash/v5.2.15/bin/bash
  args:
    - --login
working_directory: /Users/mbattiston
cursor:
  text: CellBackground
  cursor: CellForeground
cursor:
  style:
    shape: underline
    blinking: on
mouse:
  hide_when_typing: true
